---
collections:
  - name: community.general
  - name: ansible.posix

roles:
  # Role: create-user
  - name: ryandaniels.create_users
  # Role: dotfiles
  - name: geerlingguy.dotfiles
  # Role: ansible-jellyfin 
  - name: ansible-jellyfin
    src: https://github.com/Terell-Davis/ansible-jellyfin.git
  # Role: Install Docker & Manage
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: nvjacobo.caddy